# Generated by Django 6.0.6 on 2026-09-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pin',
            name='village',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
